### ISSUE TITLE
PHP Parse error: syntax error!!

### ISSUE THREAD

**Issue by EXkurumi** [PalkiaDude/Dodgeball#2]
PHP Parse error: syntax error, unexpected 'Players' (T_STRING), expecting variable (T_VARIABLE) in /var/www/tmp/5/src/Dodgeball/Main.php on line 9

I think...

class Main extends PluginBase implements Listener {
  public Players = array();
  public Status = 0;
  public User = array();
  public Time = 0;

⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩

class Main extends PluginBase implements Listener {
  public $Players = array();
  public $Status = 0;
  public $User = array();
  public $Time = 0;

I'm sorry if I'm wrong...

**Comment by dancing-ipsum** [comment]
It's not $ when the "P" is a capital. If it is a lower case letter then yes
